default:
  image:
    name: lobot-runner:latest
    pull_policy: if-not-present

workflow:
  rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      - if: $CI_PIPELINE_SOURCE == "trigger"

include:
  - local: '.gitlab/workflows/check-python-formatting.yml'

stub:
  variables:
    CAT: "MEOW"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
  script: |
    echo "meow meow $CAT"
    echo "PAYLOAD: ${PAYLOAD}" # From request
