#!/usr/bin/env sh

set -vx

# Check we're on the right branch or bail
if [ $(git branch --show-current) != "$_CREATE_MR_BRANCH_NAME" ]
then
  echo "git-create-mr expects us to be on the branch '${_CREATE_MR_BRANCH_NAME}'"
  exit 1
fi

git status -bs

# FIXME Update email to shared inbox type deal
git config user.email "whb1+gitlab@queensu.ca"
git config user.name "qsc-bot"

# FIXME Better way to remove or omit last newline
# (newlines not allowed as push options)
MR_DESCRIPTION=$(echo $MR_DESCRIPTION|tr -d '\n')

git remote set-url origin "https://qsc-bot:${LOBOT_QSC_BOT_TOK}@gitlab.cs.queensu.ca/qsc-tech-staff/lobot.git"

git status -bs

git add -- $(echo "$_CREATE_MR_ADD_PATH")

git status -bs

git commit -m "$_CREATE_MR_TITLE"
git push -u origin $_CREATE_MR_BRANCH_NAME \
  -o merge_request.create \
  -o merge_request.label=bot \
  -o merge_request.label=infra \
  -o merge_request.target="$_CREATE_MR_TARGET_BRANCH" \
  -o merge_request.title="$_CREATE_MR_TITLE" \
  -o merge_request.description="$_CREATE_MR_DESCRIPTION" \
  -o merge_request.assign="$_CREATE_MR_ASSIGNED"
