stages:
  - stage
  - check
  - test

stage_files:
  stage: stage
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
      when: never
    - when: on_success
  script: |
    echo "Checking for python files changed from 'main'..."
    git fetch origin main dev --depth 1
    git switch dev
    files=$(git diff --name-only --no-commit-id origin/main..origin/${CI_COMMIT_REF_NAME})
    py_files=$(echo -n $files | xargs -n1 echo |grep \\.py\$)
    if [ -n "$py_files" ]
    then
      echo "$py_files" > changed-python-files.txt
    fi
  artifacts:
    paths:
      - ./changed-python-files.txt

ruff_check:
  stage: check
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
      when: never
    - when: on_success
  image: python:3.12

  script:
    - |-
      if [[ ! -f ./changed-python-files.txt ]]
      then
        echo "No python files to check"
        exit 0
      fi

      CHANGED_FILES=$(cat ./changed-python-files.txt)

      pip install ruff

    - |-
      echo "Checking python syntax ..."
      ruff check ${CHANGED_FILES}

    - |-
      echo "Checking python format ..."
      ruff format --check --diff ${CHANGED_FILES}

