update_configs:
  variables:
    _CREATE_MR_BRANCH_NAME: update-jupyter-configs
    _CREATE_MR_TARGET_BRANCH: dev
    _CREATE_MR_TITLE: "chore: automated config update"
    _CREATE_MR_DESCRIPTION: >-
      This pull request was triggered by a change in the\n
      \"Cluster Users\" data source. Please cross-reference\n
      that the change here matches the corresponding items there.
    _CREATE_MR_ASSIGNED: lobot-maintainers
    _CREATE_MR_ADD_PATH: ./runtime_setting.yaml ./group-roles.yaml
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: always
  script:
    - |-
      # Write out payload
      echo "$PAYLOAD" > members-payload.json

    - INPUT_FILE=./members-payload.json
    - OUTPUT_FILE=./runtime_setting.yaml
    - |-
      # Update runtime_setting.yaml
      python3 ./.github/scripts/generate-runtime-config.py

    - INPUT_FILE: ./members-payload.json
    - OUTPUT_FILE: ./group-roles.yaml
    - |-
      # Update group-roles.yaml
      python3 ./.github/scripts/generate-group-roles.py

    - |-
      # Create Merge Request
      ./.gitlab/scripts/git-create-mr
