name: Invite GitHub user to QSC organisation

on:
  repository_dispatch:
    types: [invite-user-to-org]

jobs:
  invite_to_org:
    runs-on: ubuntu-latest
    steps:
      - name: Get user id
        id: one
        run: |
          username=${{ toJson(github.event.client_payload.username) }}
          id=$(gh api "/users/$username" --jq .id)
          echo "user_id=$id" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Git checkout
        uses: actions/checkout@v5

      - name: Send invitation to user
        run: |
          ./.github/scripts/invite-to-org.sh \
            ${{ github.repository_owner }} \
            ${{ steps.one.outputs.user_id }}
        env:
          GH_TOKEN: ${{ secrets.INVITE_BOT_TOKEN }}

