name: Invite GitHub user to QSC organisation

on:
    workflow_dispatch:

jobs:
    invite_to_org:
      runs-on: ubuntu-latest
      steps:
          - name: Get user id
            id: one
            # TODO Use name from workflow_dispatch
            run: |
              id=$(gh api /users/jm-duck | jq .id)
              echo "user_id=$id" >> $GITHUB_OUTPUT
            env:
                GH_TOKEN: ${{ github.token }}
          - name: Send invitation to user
            run: |
              org_name=${{ github.repository_owner }}
              gh api "/orgs/$org_name/invitations" \
                -F "invitee_id=${{ steps.one.outputs.user_id }}" \
                -f role=direct_member
            env:
                GH_TOKEN: ${{ secrets.INVITE_BOT_TOKEN }}

