name: Update runtime_setting.yaml

on:
  repository_dispatch:
    types: [gpu-cluster-users-changed]

jobs:
  update_file:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - name: Write out payload
        run: echo '${{ toJson(github.event.client_payload.data) }}' > members-payload.json

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install -r ./.github/scripts/requirements.txt

      - name: Update runtime_setting.yaml
        run: ./.github/scripts/generate-runtime-config
        env:
          INPUT_FILE: ./members-payload.json
          OUTPUT_FILE: ./runtime_setting.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.PR_BOT_TOKEN }}
          title: 'chore: automated runtime_setting.yaml update'
          commit-message: 'chore: automated runtime_setting.yaml update'
          body: "This pull request was triggered by a change in \
            [GPU Cluster Users](https://queensuca.sharepoint.com/teams/\
            GROUP-QSCSystemsStaff/Lists/Users/Groups.aspx). Please visually \
            cross-reference that the change here matches the corresponding items there."
          branch: update-runtime-setting
          add-paths: ./runtime_setting.yaml
          labels: infra,bot
          team-reviewers: reviewers
