name: Update runtime_setting.yaml

on:
  repository_dispatch:
    types: [gpu-cluster-users-changed]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - name: Write out payload
        run: |
          echo '${{ github.event.client_payload.data }}' > members-payload.json

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Update runtime_setting.yaml
        run: ./scripts/generate-runtime-config
