name: Update runtime_setting.yaml

on:
  repository_dispatch:
    types: [gpu-cluster-users-changed]

jobs:
  update_file:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - name: Write out payload
        run: echo '${{ toJson(github.event.client_payload.data) }}' > members-payload.json

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install -r ./scripts/requirements.txt

      - name: Update runtime_setting.yaml
        run: ./scripts/generate-runtime-config

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.PR_BOT_TOKEN }}
          title: 'chore: automated runtime_setting.yaml update'
          commit-message: 'chore: automated runtime_setting.yaml update'
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          add-paths: ./runtime_setting.yaml
          labels: infra,bot

          # Probably replace this with "team-reviewers" property at org level
          team-reviewers: reviewers
